mongodb:
  useUri: false
  uri: mongodb://localhost:27017
  host: localhost
  port: 27017
  username: user
  password: password
  database: database
  collection: collection

# Need to be implemented TODO: Implement Discord Webhook
discord:
  webhookUrl: 'YOUR_DISCORD_WEBHOOK_URL'
  message: 'Test message'

gui:
  marketplace:
    title: '&6Marketplace'
    rowSize: 3
    navigation:
        previous:
            name: '&7Previous Page'
            item: 'ARROW'
            slot: 0
        next:
            name: '&7Next Page'
            item: 'ARROW'
            slot: 8
        back:
            name: '&7Back'
            item: 'ARROW'
            slot: 4
        page:
            name: '&7Page: {page}'
            item: 'BOOK'
            slot: 1
    item:
        name: '&6{itemName}'
        lore:
            - '&7ItemType: &a{itemType}'
            - '&7Amount: &a{amount}'
            - '&7Price: &a{price}'
            - '&7Seller: &a{seller}'

permissions:
  commands:
    sell: 'marketplace.sell'
    marketplace: 'marketplace.view'

messages:
  onlyPlayer: '&cYou must be a player to use this command.'
  noPermission: '&cYou do not have permission to use this command.'
  argumentMissingSell: '&cUsage: /sell <item>'
  sellMissingItemInHand: '&cYou must hold an item in your hand to sell it.'
  wrongNumberFormat: '&cThe price must be a number. &6Your input: {input}'