settings:
  prefix: '&6[&7Marketplace&6] &7» &f'
  usePrefix: false
  closeInventoryOnReload: false
  blackmarket:
    useConfirmation: true
    maxDiscountItems: 5
  transaction:
    useGUI: false
    useHistory: true
  logging:
    mongodb: false


mongodb:
  useUri: false
  uri: mongodb://localhost:27017
  host: localhost
  port: 27017
  username: user
  password: password
  database: database
  collection: collection

discord:
  webhookUrl: 'YOUR_DISCORD_WEBHOOK_URL'
  enabled: false
  username: 'Marketplace Bot'
  content: 'Item has been bought from the Blackmarket'
  avatarUrl: 'https://example.com/avatar.png'
  embed:
    title: 'Marketplace'
    description: 'Item {itemName} bought from the Blackmarket by {playerName} for {price/discount} from {sellerName}'
    color: RED
    footer:
      text: 'Marketplace'
      icon_url: 'https://example.com/icon.png'
    thumbnail:
      url: 'https://example.com/thumbnail.png'
    image:
      url: 'https://example.com/image.png'

gui:
  adminDeeper:
    title: '&6Admin Deeper GUI'
  admin:
    title: '&6Admin GUI'
    navigation:
      previous:
        name: '&7Previous Page'
        item: 'ARROW'
        slot: 0
      next:
        name: '&7Next Page'
        item: 'ARROW'
        slot: 8
      back:
        name: '&7Back'
        item: 'ARROW'
        slot: 4
      page:
        name: '&7Page: {page}'
        item: 'BOOK'
        slot: 1
    item:
      name: '&6{itemName}'
      lore:
        - '&7ItemType: &a{itemType}'
        - '&7Sold: &a{sold}'
        - '&7Seller: &a{seller}'
        - '&7Receiver: &a{receiver}'
  updateDeeper:
    title: '&6Update Deeper GUI'
    renameItem:
      name: "&6Rename Item"
      item: "NAME_TAG"
    changePrice:
      name: "&6Change Price"
      item: "GOLD_INGOT"
    deleteItem:
      name: "&6Delete Item"
      item: "BARRIER"
    back:
      name: "&7Back"
      item: "ARROW"
  update:
    title: '&6Update Item'
    rowSize: 3
    navigation:
      previous:
        name: '&7Previous Page'
        item: 'ARROW'
        slot: 0
      next:
        name: '&7Next Page'
        item: 'ARROW'
        slot: 8
      back:
        name: '&7Back'
        item: 'ARROW'
        slot: 4
      page:
        name: '&7Page: {page}'
        item: 'BOOK'
        slot: 1
    discount: '&6DISCOUNT 50% new price {newPrice}'
  confirmation:
    title: '&6Confirmation'
  transaction:
    title: '&6Transactions'
    rowSize: 3
  marketplace:
    title: '&6Marketplace'
    rowSize: 3
    navigation:
      previous:
        name: '&7Previous Page'
        item: 'ARROW'
        slot: 0
      next:
        name: '&7Next Page'
        item: 'ARROW'
        slot: 8
      back:
        name: '&7Back'
        item: 'ARROW'
        slot: 4
      page:
        name: '&7Page: {page}'
        item: 'BOOK'
        slot: 1
      updateItem:
        name: '&7Update Items'
        item: 'STONE'
        slot: 2
    item:
      name: '&6{itemName}'
      lore:
        - '&7ItemType: &a{itemType}'
        - '&7Amount: &a{amount}'
        - '&7Price: &a{price}'
        - '&7Seller: &a{seller}'
      discount: '&6DISCOUNT 50% new price {newPrice}'
  blackmarket:
    title: '&6Black Market'
    rowSize: 3
    navigation:
      previous:
        name: '&7Previous Page'
        item: 'ARROW'
        slot: 0
      next:
        name: '&7Next Page'
        item: 'ARROW'
        slot: 8
      back:
        name: '&7Back'
        item: 'ARROW'
        slot: 4
      page:
        name: '&7Page: {page}'
        item: 'BOOK'
        slot: 1
      yourItems:
        name: '&7Your Items'
        item: 'DIAMOND_BLOCK'
        slot: 2
    item:
      name: '&6{itemName}'
      lore:
        - '&7ItemType: &a{itemType}'
        - '&7Amount: &a{amount}'
        - '&7Price: &a{price}'
        - '&7Seller: &a{seller}'
      discount: '&6DISCOUNT 50% new price {newPrice}'

permissions:
  commands:
    sell: 'marketplace.sell'
    marketplace: 'marketplace.view'
    transactions: 'marketplace.history'
    blackmarket: 'marketplace.blackmarket'
    marketplace-admin: 'marketplace.admin'

messages:
  onlyPlayer: '&cYou must be a player to use this command.'
  noPermission: '&cYou do not have permission to use this command.'
  sell:
    itemAdded: '&7You have successfully added the Item &6{itemName} &6{amount}x &7for
      the price &6{price} &7to the Marketplace!'
    argumentMissing: '&cUsage: /sell <item>'
    missingItemInHand: '&cYou must hold an item in your hand to sell it.'
    wrongNumberFormat: '&cThe price must be a number. &6Your input: {input}'
    itemSold: '&7You have sold &6{amount}x {itemName} &7for &6{price} &7to the Player &6{playerName}.'
    boughtItem: '&7You bought the item &6{itemName} &7from &6{playerName} {amount}x.'
  error:
    sell: '&cThere was an error selling the Item &6{itemName}&c!'
    buy: '&cThere was an error buying the Item &6{itemName}&c!'
    updatingTransaction: 'There was an error while updating Transaction! {id}'
    addTransaction: 'There was an error while adding new Transaction! {id}'
    itemMetaNotFound: '&cItemMeta for &6{itemName} &c not found!'
    moneyNotEnough: '&cYou do not have enough money to buy this item!'
    executeDiscordWebhook: 'There was an error while executing Discord Webhook!'