name: MarketPlacePlugin
version: '1.0-SNAPSHOT'
main: ch.framedev.marketplace.main.Main
api-version: '1.21'
depend:
  - Vault
libraries:
  - org.apache.logging.log4j:log4j-api:2.22.1
  - org.apache.logging.log4j:log4j-core:2.22.1
  - org.apache.logging.log4j:log4j-slf4j2-impl:2.22.1
  - org.mongodb:mongodb-driver-sync:4.10.0
commands:
  sell:
  marketplace:
    description: Opens the marketplace GUI.
    usage: /marketplace
    aliases: [mp]
  blackmarket:
    description: Opens the black market GUI.
    usage: /blackmarket
    aliases: [bmp]
  transactions:
    usage: /transactions
  marketplace-admin:
    usage: /marketplace-admin